"""Fit Argos-style ``inference(sample)`` rules on paperib train (no LLM).

Rules follow the official Argos contract: ``sample`` is ``(N, 2)`` of
``(value, index)`` → binary labels length ``N``. Thresholds are fit on the
train fold only (using labels only to report fit stats; decision uses
train-normal quantiles so inference never reads labels).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


def fit_rate_drop_rule(
    train_df: pd.DataFrame,
    *,
    q_low: float = 0.02,
    roll: int = 12,
    drop_ratio: float = 0.55,
) -> tuple[str, dict[str, Any]]:
    """Heuristic for SUCCESS/ACCEPT-like rates (lower = worse)."""
    values = train_df["value"].to_numpy(dtype=np.float64)
    labels = train_df["label"].to_numpy(dtype=int)
    normal = values[labels == 0] if (labels == 0).any() else values
    abs_thr = float(np.nanquantile(normal, q_low))
    # Relative drop vs trailing median inside the chunk (encoded as constants
    # + roll/drop_ratio for the generated function).
    meta = {
        "kind": "rate_drop",
        "abs_thr": abs_thr,
        "q_low": q_low,
        "roll": int(roll),
        "drop_ratio": float(drop_ratio),
        "train_n": int(len(values)),
        "train_anom": int(labels.sum()),
    }
    code = f'''# Autogenerated IB heuristic (no LLM) — Argos inference contract
# Paperib rate-drop: absolute floor + drop vs rolling median.
import numpy as np

def inference(sample: np.ndarray) -> np.ndarray:
    # Normal Rule 1: rate stays near local median for quiet periods
    # Normal Rule 2: rare dips below train-normal quantile are anomalous
    # Abnormal Rule 1: value below absolute train quantile
    # Abnormal Rule 2: value << recent rolling median (sustained degrade)
    x = np.asarray(sample, dtype=float)
    if x.ndim != 2 or x.shape[1] < 1:
        return np.zeros(len(x), dtype=int)
    v = x[:, 0]
    n = len(v)
    out = np.zeros(n, dtype=int)
    abs_thr = {abs_thr!r}
    roll = {int(roll)}
    drop_ratio = {float(drop_ratio)!r}
    out[v < abs_thr] = 1
    if n >= max(3, roll // 2):
        s = pd_series(v)
        med = s.rolling(roll, min_periods=max(3, roll // 3), center=False).median().to_numpy()
        rel = (v < (med * drop_ratio)) & np.isfinite(med) & (med > abs_thr * 0.5)
        out[rel] = 1
    return out

def pd_series(v):
    import pandas as pd
    return pd.Series(v)
'''
    # Prefer pure numpy rolling median to avoid requiring pandas inside exec env quirks
    code = f'''# Autogenerated IB heuristic (no LLM) — Argos inference contract
# Paperib rate-drop: absolute floor + drop vs trailing median.
import numpy as np

def inference(sample: np.ndarray) -> np.ndarray:
    # Normal Rule 1: rate near local level in quiet windows
    # Abnormal Rule 1: below train-normal low quantile ({q_low})
    # Abnormal Rule 2: sharp drop vs trailing median
    x = np.asarray(sample, dtype=float)
    if x.ndim != 2 or x.shape[1] < 1:
        return np.zeros((0,), dtype=int)
    v = x[:, 0]
    n = int(v.shape[0])
    out = np.zeros(n, dtype=int)
    abs_thr = {abs_thr!r}
    roll = {int(roll)}
    drop_ratio = {float(drop_ratio)!r}
    out[np.isfinite(v) & (v < abs_thr)] = 1
    if n >= 3:
        med = np.full(n, np.nan)
        for i in range(n):
            a = max(0, i - roll + 1)
            window = v[a : i + 1]
            window = window[np.isfinite(window)]
            if len(window) >= max(2, roll // 3):
                med[i] = float(np.median(window))
        rel = (
            np.isfinite(v)
            & np.isfinite(med)
            & (med > max(abs_thr * 0.5, 1e-6))
            & (v < med * drop_ratio)
        )
        out[rel] = 1
    return out
'''
    return code, meta


def fit_count_spike_rule(
    train_df: pd.DataFrame,
    *,
    q_high: float = 0.99,
) -> tuple[str, dict[str, Any]]:
    """Heuristic for attempt/fail-like counts (higher = worse)."""
    values = train_df["value"].to_numpy(dtype=np.float64)
    labels = train_df["label"].to_numpy(dtype=int)
    normal = values[labels == 0] if (labels == 0).any() else values
    abs_thr = float(np.nanquantile(normal, q_high))
    meta = {
        "kind": "count_spike",
        "abs_thr": abs_thr,
        "q_high": q_high,
        "train_n": int(len(values)),
        "train_anom": int(labels.sum()),
    }
    code = f'''# Autogenerated IB heuristic (no LLM) — Argos inference contract
# Paperib count spike: above train-normal high quantile.
import numpy as np

def inference(sample: np.ndarray) -> np.ndarray:
    # Normal Rule 1: counts stay below train high quantile
    # Abnormal Rule 1: value exceeds train-normal q{q_high}
    x = np.asarray(sample, dtype=float)
    if x.ndim != 2 or x.shape[1] < 1:
        return np.zeros((0,), dtype=int)
    v = x[:, 0]
    out = np.zeros(len(v), dtype=int)
    abs_thr = {abs_thr!r}
    out[np.isfinite(v) & (v > abs_thr)] = 1
    return out
'''
    return code, meta


def fit_rule_for_metric(
    metric: str, train_df: pd.DataFrame
) -> tuple[str, dict[str, Any]]:
    m = metric.upper()
    if m in ("S_RATE", "A_RATE") or "RATE" in m:
        return fit_rate_drop_rule(train_df)
    return fit_count_spike_rule(train_df)


def write_rule(path: Path | str, code: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(code, encoding="utf-8")
    return path
